name = "milou"
description = ""
version = "0.1.0-dev"

authors = ["Tristan DHERSIN"]
maintainers = ["Tristan DHERSIN <tristan.dhersin@gmail.com>"]
maintainers-logins = ["TristanBrouille"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
nucleo_g431kb = "*"

[[pins]]
nucleo_g431kb = { path = "/home/henley/Desktop/stm32_dev/nucleo_g431kb"}